// Generated by scripts/harness-manifest.mjs. Do not edit by hand; rerun the script when pins move.
import type { ProgramManifest } from "./types";

export const HARNESS_MANIFEST: ProgramManifest = {
  codex: {
    version: "0.160.0",
    platforms: {
      "darwin-arm64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-aarch64-apple-darwin.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "d9206758c252f10a4cc51fcca45d3321f5e386b57c3657d11caaf61c5d3d5ce2",
          size: 93874548,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "112fae7a5a1223e673c8a1791d32338f37df8b527ff1159bb8adac6c4dbf1b4b",
          size: 241555024,
        },
      },
      "darwin-x64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-x86_64-apple-darwin.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "e37ae66eefbf7571eae40518676e4119ea92ed2136e66d8a0ca885e984bb0c5c",
          size: 102998566,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "5383ef71dd1bd8d2f3658c04a219e2cf165c7969aebd0cceced1bc9f0f68877f",
          size: 260633072,
        },
      },
      "linux-arm64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-aarch64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "83d68fdeb6022722b66f50459363aa43f55ce0fb70778aa1cfeaa70e46ce97fe",
          size: 109633979,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "50b06603bdcdac39b714f5c3e68583c002b8ad8779ebfdaaf4932ff016b379c0",
          size: 248966648,
        },
      },
      "linux-x64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-x86_64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "c98a0003f1c858676c52f20c93f3832761c899e331c44ea15d8e20634626a4c2",
          size: 115769608,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "12eb3e81114588aca3b7998f4f19e8997b056aca08e57a7ca7c8a3ec8c652aad",
          size: 289101384,
        },
      },
      "linux-arm64-musl": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-aarch64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "83d68fdeb6022722b66f50459363aa43f55ce0fb70778aa1cfeaa70e46ce97fe",
          size: 109633979,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "50b06603bdcdac39b714f5c3e68583c002b8ad8779ebfdaaf4932ff016b379c0",
          size: 248966648,
        },
      },
      "linux-x64-musl": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-x86_64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "c98a0003f1c858676c52f20c93f3832761c899e331c44ea15d8e20634626a4c2",
          size: 115769608,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "12eb3e81114588aca3b7998f4f19e8997b056aca08e57a7ca7c8a3ec8c652aad",
          size: 289101384,
        },
      },
      "win32-arm64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-aarch64-pc-windows-msvc.tar.zst",
        file: "bin/codex.exe",
        download: {
          sha256:
            "b73719b94d94ae6377fe10a596c20d9527f0cca3732048fb69ecff286b1a77ed",
          size: 108775952,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "1f090167e94ed25969c47381868c6ffb78be2a195e13891fcdc969531ca16eaf",
          size: 274925872,
        },
      },
      "win32-x64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-x86_64-pc-windows-msvc.tar.zst",
        file: "bin/codex.exe",
        download: {
          sha256:
            "f1053d8592da7938fe39156911bcd823caa43c766e5d3d0939a34db0aab60dd1",
          size: 117446483,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "fdda5fa3cf3fb3d000b876720742857676293e4315e4b045fae6f8bd7e866d1d",
          size: 326872368,
        },
      },
    },
  },
  claude: {
    version: "2.1.286",
    platforms: {
      "darwin-arm64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/darwin-arm64/claude",
        file: "claude",
        download: {
          sha256:
            "75e3016e9d2570767b08e43a7467d4817a4f149232c169ca295f2c95fef21433",
          size: 225167728,
        },
      },
      "darwin-x64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/darwin-x64/claude",
        file: "claude",
        download: {
          sha256:
            "53e6a936e89519d695230f9cc97943991286b72766674fba11bee845f0a7c047",
          size: 233607424,
        },
      },
      "linux-arm64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/linux-arm64/claude",
        file: "claude",
        download: {
          sha256:
            "0292fa22ac2fd43e16be9d0e511ddd8347280d6e0ebaca744ef5b27e05d8d0f8",
          size: 241033208,
        },
      },
      "linux-x64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/linux-x64/claude",
        file: "claude",
        download: {
          sha256:
            "fe503f65c6289d59c23e5b21ae44f03583f997dd33a2cbfc75ab4f96fb8fc73f",
          size: 241667256,
        },
      },
      "linux-arm64-musl": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/linux-arm64-musl/claude",
        file: "claude",
        download: {
          sha256:
            "5b9b9e41b8b347ba573924342b29b1133d88a7bec51362d5a90a9f22cd6f76cf",
          size: 233387840,
        },
      },
      "linux-x64-musl": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/linux-x64-musl/claude",
        file: "claude",
        download: {
          sha256:
            "410780234cc3e54afe41a958ef26a4b4f1d253849b769c760f6bcf0bb525fb09",
          size: 235417688,
        },
      },
      "win32-x64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/win32-x64/claude.exe",
        file: "claude.exe",
        download: {
          sha256:
            "0b6ecec8edef1ce3069682f696c894d1553239faa6b84e56e167a3ced88fa333",
          size: 245092000,
        },
      },
      "win32-arm64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/win32-arm64/claude.exe",
        file: "claude.exe",
        download: {
          sha256:
            "9109c7b0a0de5b40fd013b9009411e517199c8275d2363b824e851cc1133d3c3",
          size: 232616096,
        },
      },
    },
  },
  opencode: {
    version: "1.18.34",
    platforms: {
      "darwin-arm64": {
        url: "https://registry.npmjs.org/opencode-darwin-arm64/-/opencode-darwin-arm64-1.18.34.tgz",
        file: "package/bin/opencode",
        download: {
          sha256:
            "9a336191ee84c8f54364b5d1990ec87abb2acbb00dea189f11dda5e968d7bf05",
          size: 45264760,
        },
        compression: "gzip",
        archive: "tar",
        binary: {
          sha256:
            "7b63b34fafabded7d9231f6a9032755d0cdeaf8b9d2b70df8e25535471469eea",
          size: 144257280,
        },
      },
      "darwin-x64": {
        url: "https://registry.npmjs.org/opencode-darwin-x64/-/opencode-darwin-x64-1.18.34.tgz",
        file: "package/bin/opencode",
        download: {
          sha256:
            "bda35c563697ca66b2b5c5b51f6f731376de4b007d9134a52cfe6b8216acba0a",
          size: 48879002,
        },
        compression: "gzip",
        archive: "tar",
        binary: {
          sha256:
            "f97abb1fb2e701b4a4bcc06361e41c81d1837d9e60c3e7d65dfaca9827422ac3",
          size: 151188432,
        },
      },
      "linux-arm64": {
        url: "https://registry.npmjs.org/opencode-linux-arm64/-/opencode-linux-arm64-1.18.34.tgz",
        file: "package/bin/opencode",
        download: {
          sha256:
            "6f212b830b26bf72012f1665559ddb5fd7e928294971d3d1c99a0f9097a3d311",
          size: 60094599,
        },
        compression: "gzip",
        archive: "tar",
        binary: {
          sha256:
            "415487fcd9b3f06addd6877435783f3d5a236c029066b0dd6597d64980b15351",
          size: 185116816,
        },
      },
      "linux-x64": {
        url: "https://registry.npmjs.org/opencode-linux-x64/-/opencode-linux-x64-1.18.34.tgz",
        file: "package/bin/opencode",
        download: {
          sha256:
            "b83e8ac66d752d05ead4b6a439d3a2cfa32bcd9817c708825a389b5d5cba4f19",
          size: 60309530,
        },
        compression: "gzip",
        archive: "tar",
        binary: {
          sha256:
            "9ca0b9953d49997601655e54f846a3efa464f237e47c6f1b04716d0f2e64c4c2",
          size: 185632896,
        },
      },
      "linux-arm64-musl": {
        url: "https://registry.npmjs.org/opencode-linux-arm64-musl/-/opencode-linux-arm64-musl-1.18.34.tgz",
        file: "package/bin/opencode",
        download: {
          sha256:
            "f2c712c6279960802615e8e1c2db150dbfd0c7aec02003001813b9d58b623a6d",
          size: 62202895,
        },
        compression: "gzip",
        archive: "tar",
        binary: {
          sha256:
            "0fc925d7f8f9562c90cd9d684ac96baadedb360e75602f074942a484bcecfa75",
          size: 194621304,
        },
      },
      "linux-x64-musl": {
        url: "https://registry.npmjs.org/opencode-linux-x64-musl/-/opencode-linux-x64-musl-1.18.34.tgz",
        file: "package/bin/opencode",
        download: {
          sha256:
            "60b301c9918d9a30ef42dab7096d5528e8c0dc5028bd70eb86864082177a12d5",
          size: 62664505,
        },
        compression: "gzip",
        archive: "tar",
        binary: {
          sha256:
            "4fa437184846977f1849ffb65fc19d32686dec85a455df3d37f69a2993f22182",
          size: 196049184,
        },
      },
      "win32-arm64": {
        url: "https://registry.npmjs.org/opencode-windows-arm64/-/opencode-windows-arm64-1.18.34.tgz",
        file: "package/bin/opencode.exe",
        download: {
          sha256:
            "b9dfab4ffcd5df5a9286d613359701dd6c8d3d880f0c426ba7a7c37eb5a7aeeb",
          size: 58544117,
        },
        compression: "gzip",
        archive: "tar",
        binary: {
          sha256:
            "f229c557fa54e3b2c79d78e31dc14b4e1447047b04a339ec62353e3586a7ab0f",
          size: 176494984,
        },
      },
      "win32-x64": {
        url: "https://registry.npmjs.org/opencode-windows-x64/-/opencode-windows-x64-1.18.34.tgz",
        file: "package/bin/opencode.exe",
        download: {
          sha256:
            "b4f4ae37a9ecbd6eceecf3a452573a5abdeab88ba50f93a9ad40762d7a10bae9",
          size: 60230073,
        },
        compression: "gzip",
        archive: "tar",
        binary: {
          sha256:
            "5283c2cd5b4285855daa97e6f7d17bf48146227cdf2a940e79e0f2b7869fd06e",
          size: 180599176,
        },
      },
    },
  },
};
