// Generated by scripts/harness-manifest.mjs. Do not edit by hand; rerun the script when pins move.
import type { ProgramManifest } from "./types";

export const HARNESS_MANIFEST: ProgramManifest = {
  codex: {
    version: "0.155.1",
    platforms: {
      "darwin-arm64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.155.1/codex-package-aarch64-apple-darwin.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "f31d84b9ad8dddd3763e441871008df82ecc803d1ec273d25fc5e26b0ce31673",
          size: 89295596,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "8eaf1ad12fe6bf89b1710330f58900014322c7c5af677e43be116d8ac5fc0a9e",
          size: 228803200,
        },
      },
      "darwin-x64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.155.1/codex-package-x86_64-apple-darwin.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "637d3897fcc7b36e3562961a139b34313dff016aec9b9e8aed71a88382c50605",
          size: 97886284,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "3e824474baa0667a19547f3b3633c091579163b5ffd03c976fb376d773479eac",
          size: 245974512,
        },
      },
      "linux-arm64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.155.1/codex-package-aarch64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "4238cb9be3eae4ab683c087907a881ec52b84a39c80fa4358803abb85e2c84db",
          size: 95763508,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "298d3d73d0bbc1367e58a370df5b6216fe30ce0a92e8b6b0afb0377a958dc335",
          size: 232726912,
        },
      },
      "linux-x64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.155.1/codex-package-x86_64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "8312d172da663e4eb4b809447dcf12e248d5174ae18d68e54bbd4c92d37bd8ae",
          size: 101320931,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "0753dfe1d8b87a52436deb13eb1c549661ef4c84fee2c5aa688385eebeccb761",
          size: 269273536,
        },
      },
      "linux-arm64-musl": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.155.1/codex-package-aarch64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "4238cb9be3eae4ab683c087907a881ec52b84a39c80fa4358803abb85e2c84db",
          size: 95763508,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "298d3d73d0bbc1367e58a370df5b6216fe30ce0a92e8b6b0afb0377a958dc335",
          size: 232726912,
        },
      },
      "linux-x64-musl": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.155.1/codex-package-x86_64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "8312d172da663e4eb4b809447dcf12e248d5174ae18d68e54bbd4c92d37bd8ae",
          size: 101320931,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "0753dfe1d8b87a52436deb13eb1c549661ef4c84fee2c5aa688385eebeccb761",
          size: 269273536,
        },
      },
      "win32-arm64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.155.1/codex-package-aarch64-pc-windows-msvc.tar.zst",
        file: "bin/codex.exe",
        download: {
          sha256:
            "f8ca4ee8ceced787e10b9c94c540a5993a69a60a8e21f6fade844e816fd8cef3",
          size: 96952926,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "30bbe48875b79f8c4715d079812e9ca82176870e948992324abb941c15e4d5f6",
          size: 258754352,
        },
      },
      "win32-x64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.155.1/codex-package-x86_64-pc-windows-msvc.tar.zst",
        file: "bin/codex.exe",
        download: {
          sha256:
            "2b66a491fff1406d112c6c6cf403ceb4033f58495ccb3aa5cd69e00f21039241",
          size: 104608720,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "eba0f32c976667cb9298efafd98513e823eeda7b576a03ec658bb8be8d336316",
          size: 307108144,
        },
      },
    },
  },
  claude: {
    version: "2.1.280",
    platforms: {
      "darwin-arm64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.280/darwin-arm64/claude",
        file: "claude",
        download: {
          sha256:
            "387a5c5dcdbb815085edf0baf79591f9d8894efe922bceaf3d75b1b08055229d",
          size: 217254576,
        },
      },
      "darwin-x64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.280/darwin-x64/claude",
        file: "claude",
        download: {
          sha256:
            "c1d32d87630482250633208ab77855429b24010ae3086a7ff7539b57b93168d4",
          size: 225565024,
        },
      },
      "linux-arm64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.280/linux-arm64/claude",
        file: "claude",
        download: {
          sha256:
            "92f2b4fd05d0bdcf7b9a0d4e0ecef4a1e4b368b290cd8fd07cff9a50013f45a2",
          size: 233103352,
        },
      },
      "linux-x64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.280/linux-x64/claude",
        file: "claude",
        download: {
          sha256:
            "1e08503dbdf3c2cb0d706d32f3408277388d1c76ef108673e8fe42c1b322925b",
          size: 233709640,
        },
      },
      "linux-arm64-musl": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.280/linux-arm64-musl/claude",
        file: "claude",
        download: {
          sha256:
            "6a9f349dccd1c74ab854f1877c5ebdf074998571d0177e26c1f7f46f29e0f971",
          size: 225457992,
        },
      },
      "linux-x64-musl": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.280/linux-x64-musl/claude",
        file: "claude",
        download: {
          sha256:
            "8d25ffbf600882d7b985706cc10ea45995060637ed009b5700b65e162bb00b96",
          size: 227467360,
        },
      },
      "win32-x64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.280/win32-x64/claude.exe",
        file: "claude.exe",
        download: {
          sha256:
            "0e4195524b73eb77efbdf3e2b36de5322a29f0ca575dfd2d9b4f946b1d425469",
          size: 237100192,
        },
      },
      "win32-arm64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.280/win32-arm64/claude.exe",
        file: "claude.exe",
        download: {
          sha256:
            "f49980314f4c0418079979723ffd6c0d00d57e60b26fd95c53e53155ed913bdf",
          size: 225107104,
        },
      },
    },
  },
};
