// Generated by scripts/harness-manifest.mjs. Do not edit by hand; rerun the script when pins move.
import type { ProgramManifest } from "./types";

export const HARNESS_MANIFEST: ProgramManifest = {
  codex: {
    version: "0.160.0",
    platforms: {
      "darwin-arm64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-aarch64-apple-darwin.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "d9206758c252f10a4cc51fcca45d3321f5e386b57c3657d11caaf61c5d3d5ce2",
          size: 93874548,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "112fae7a5a1223e673c8a1791d32338f37df8b527ff1159bb8adac6c4dbf1b4b",
          size: 241555024,
        },
      },
      "darwin-x64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-x86_64-apple-darwin.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "e37ae66eefbf7571eae40518676e4119ea92ed2136e66d8a0ca885e984bb0c5c",
          size: 102998566,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "5383ef71dd1bd8d2f3658c04a219e2cf165c7969aebd0cceced1bc9f0f68877f",
          size: 260633072,
        },
      },
      "linux-arm64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-aarch64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "83d68fdeb6022722b66f50459363aa43f55ce0fb70778aa1cfeaa70e46ce97fe",
          size: 109633979,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "50b06603bdcdac39b714f5c3e68583c002b8ad8779ebfdaaf4932ff016b379c0",
          size: 248966648,
        },
      },
      "linux-x64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-x86_64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "c98a0003f1c858676c52f20c93f3832761c899e331c44ea15d8e20634626a4c2",
          size: 115769608,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "12eb3e81114588aca3b7998f4f19e8997b056aca08e57a7ca7c8a3ec8c652aad",
          size: 289101384,
        },
      },
      "linux-arm64-musl": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-aarch64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "83d68fdeb6022722b66f50459363aa43f55ce0fb70778aa1cfeaa70e46ce97fe",
          size: 109633979,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "50b06603bdcdac39b714f5c3e68583c002b8ad8779ebfdaaf4932ff016b379c0",
          size: 248966648,
        },
      },
      "linux-x64-musl": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-x86_64-unknown-linux-musl.tar.zst",
        file: "bin/codex",
        download: {
          sha256:
            "c98a0003f1c858676c52f20c93f3832761c899e331c44ea15d8e20634626a4c2",
          size: 115769608,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "12eb3e81114588aca3b7998f4f19e8997b056aca08e57a7ca7c8a3ec8c652aad",
          size: 289101384,
        },
      },
      "win32-arm64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-aarch64-pc-windows-msvc.tar.zst",
        file: "bin/codex.exe",
        download: {
          sha256:
            "b73719b94d94ae6377fe10a596c20d9527f0cca3732048fb69ecff286b1a77ed",
          size: 108775952,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "1f090167e94ed25969c47381868c6ffb78be2a195e13891fcdc969531ca16eaf",
          size: 274925872,
        },
      },
      "win32-x64": {
        url: "https://github.com/openai/codex/releases/download/rust-v0.160.0/codex-package-x86_64-pc-windows-msvc.tar.zst",
        file: "bin/codex.exe",
        download: {
          sha256:
            "f1053d8592da7938fe39156911bcd823caa43c766e5d3d0939a34db0aab60dd1",
          size: 117446483,
        },
        compression: "zstd",
        archive: "tar",
        binary: {
          sha256:
            "fdda5fa3cf3fb3d000b876720742857676293e4315e4b045fae6f8bd7e866d1d",
          size: 326872368,
        },
      },
    },
  },
  claude: {
    version: "2.1.286",
    platforms: {
      "darwin-arm64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/darwin-arm64/claude",
        file: "claude",
        download: {
          sha256:
            "75e3016e9d2570767b08e43a7467d4817a4f149232c169ca295f2c95fef21433",
          size: 225167728,
        },
      },
      "darwin-x64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/darwin-x64/claude",
        file: "claude",
        download: {
          sha256:
            "53e6a936e89519d695230f9cc97943991286b72766674fba11bee845f0a7c047",
          size: 233607424,
        },
      },
      "linux-arm64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/linux-arm64/claude",
        file: "claude",
        download: {
          sha256:
            "0292fa22ac2fd43e16be9d0e511ddd8347280d6e0ebaca744ef5b27e05d8d0f8",
          size: 241033208,
        },
      },
      "linux-x64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/linux-x64/claude",
        file: "claude",
        download: {
          sha256:
            "fe503f65c6289d59c23e5b21ae44f03583f997dd33a2cbfc75ab4f96fb8fc73f",
          size: 241667256,
        },
      },
      "linux-arm64-musl": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/linux-arm64-musl/claude",
        file: "claude",
        download: {
          sha256:
            "5b9b9e41b8b347ba573924342b29b1133d88a7bec51362d5a90a9f22cd6f76cf",
          size: 233387840,
        },
      },
      "linux-x64-musl": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/linux-x64-musl/claude",
        file: "claude",
        download: {
          sha256:
            "410780234cc3e54afe41a958ef26a4b4f1d253849b769c760f6bcf0bb525fb09",
          size: 235417688,
        },
      },
      "win32-x64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/win32-x64/claude.exe",
        file: "claude.exe",
        download: {
          sha256:
            "0b6ecec8edef1ce3069682f696c894d1553239faa6b84e56e167a3ced88fa333",
          size: 245092000,
        },
      },
      "win32-arm64": {
        url: "https://downloads.claude.ai/claude-code-releases/2.1.286/win32-arm64/claude.exe",
        file: "claude.exe",
        download: {
          sha256:
            "9109c7b0a0de5b40fd013b9009411e517199c8275d2363b824e851cc1133d3c3",
          size: 232616096,
        },
      },
    },
  },
};
